server:
  port: 8086

spring:
  application:
    name: uaa-service
  datasource:
    url: jdbc:mysql://localhost:3306/user_db?useUnicode=true&characterEncoding=utf8
    username: root
    password: 784243
    driver-class-name: com.mysql.jdbc.Driver

  main:
    allow-bean-definition-overriding: true
  http:
    encoding:
      enabled: true
      charset: utf-8
      force: true



  redis:
    host: 127.0.0.1
    port: 6379
    password:
    database: 0
    lettuce:
      pool:
        max-active: 32
        max-wait: 300ms
        max-idle: 16
        min-idle: 8

mybatis:
  configuration:
    map-underscore-to-camel-case: true


feign:
  hystrix:
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/